services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://api.husniramandalubis.com/api
    container_name: mini_frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mini_backend
    ports:
      - "8081:8081"
    env_file:
      - ./api/.env
    restart: unless-stopped