-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "eventDescription" DROP NOT NULL,
ALTER COLUMN "eventTnC" DROP NOT NULL,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "deletedAt" DROP NOT NULL;

-- AlterTable
ALTER TABLE "TicketType" ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "status" SET DEFAULT 'HIDDEN';

-- AlterTable
ALTER TABLE "Venue" ALTER COLUMN "region" DROP NOT NULL,
ALTER COLUMN "latitude" DROP NOT NULL,
ALTER COLUMN "longitude" DROP NOT NULL;
